# Site settings
title: portfolio
email: erickouellette1105@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Voici mon portfolio"
keywords: "your keywords, separated by commas"
skills: "Compétences:
Maya, Da Vinci, Vcv Rack, Unity, Figma, Photoshop "
meta_author: Ouellette Érick

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jérome Lachaud 
  location: Lieu
  social: 
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Erickthe
  - title: linkedin
    url: https://www.linkedin.com/in/%C3%A9rick-ouellette-aa4573293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app

# Postal address (add as many lines as necessary)
address:
  - line: Montréal
  - line: 

# Credits content
credits: 'Freelancer est un thème Bootstrap open source et gratuit créé par <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
